repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: goimports
        name: goimports
        description: Run goimports on the repository
        entry: go tool goimports -local github.com/sumnerevans/offlinemsmtp -w .
        language: system
        pass_filenames: false
        types: [go]
      - id: staticcheck
        name: staticcheck
        description: Run staticcheck on the repository
        entry: go tool staticcheck ./...
        language: system
        pass_filenames: false
        types: [go]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-vet-repo-mod
      - id: go-mod-tidy-repo

  - repo: https://github.com/beeper/pre-commit-go
    rev: v0.4.2
    hooks:
      - id: prevent-literal-http-methods
      - id: zerolog-ban-global-log
      - id: zerolog-ban-msgf
      - id: zerolog-use-stringer
