image: nixos/unstable
packages:
  - nixos.python38Packages.poetry
  - nixos.cairo
  - nixos.gobject-introspection
sources:
  - https://git.sr.ht/~sumner/offlinemsmtp
secrets:
  # PyPi Deploy Credentials for Offlinemsmtp
  - 812d576d-403c-4093-944e-ff3a8d07cfc0
environment:
  REPO_NAME: offlinemsmtp
# triggers:
#   - action: email
#     condition: failure
#     to: ~sumner/offlinemsmtp-devel@lists.sr.ht
tasks:
  - setup: |
      cd ${REPO_NAME}
      nix-shell --command "poetry install"
      echo "cd ${REPO_NAME}" >> ~/.buildenv

  - lint: |
      nix-shell --command "source $(poetry env info -p)/bin/activate &&
        poetry check &&
        flake8 &&
        mypy offlinemsmtp &&
        black --check . &&
        .builds/bin/custom_style_check.py"

  - build: |
      nix-shell --command "poetry build"

  - test-deploy: |
      nix-shell --command "poetry publish --dry-run"

  - deploy: |
      .builds/bin/tagged_with_version || echo "Skipping deploy since not tagged with version"
      .builds/bin/tagged_with_version || complete-build
      nix-shell --command "poetry publish"
